### ISSUE TITLE
Wrong racer name in live race results view

### ISSUE THREAD

**Issue by zhvial** [micbay/RaceTimerAndController#1]
Even through  you change racer name in menu - live race display shows racer names 1 and 2 from Racers[] array. 7 segment display shows correct names, end results are also corrrect, but live race display and "finish" display is not correct. Also winning melody is playing for first or second racer from array, whatever racer you have selected  before from menu.

Here is the video where I'm showing the bug 
[https://youtu.be/86N7HagvqQE](https://www.youtube.com/watch?v=86N7HagvqQE)

**Comment by zhvial** [comment]
I've found how to solve the problem.
I do not know how to make pull request so posting here:

line 2085:
startPlayRtttlPGM(buzzPin1, victorySong[laneRacer[i]]);

line 2113
startPlayRtttlPGM(buzzPin1, victorySong[laneRacer[leaderBoard[0][1]]]);


line 1453

PrintText(Racers[laneRacer[leaderBoard[k-1][1]]], lcdDisp, 11, 6, false, k);

line 1458

PrintText(Racers[laneRacer[overallFastestRacer]], lcdDisp, 19, 6, false, 3);

**Comment by micbay** [comment]
I have added the above changes and the current master branch should now contain the fix. Thanks for finding it and posting it.
