### ISSUE TITLE
Loop in race laptimer and name

### ISSUE THREAD

**Issue by sommo** [micbay/RaceTimerAndController#12]
Hi @micbay, I get it working (the startlightI2C) version.
But when choosing racer the display name is incomplete:
![image](https://user-images.githubusercontent.com/22022996/224379239-f8cea5b2-0c34-413c-8edb-00129201cabc.jpeg)
Also the chained one

![image](https://user-images.githubusercontent.com/22022996/224379386-c4ff16c7-187d-4109-9074-1b361c3c7211.jpeg)

Once the race is started, it seems getting in loop:
https://user-images.githubusercontent.com/22022996/224379609-51754355-ae42-4162-b391-85388f1c4b57.MOV

I didn't soldered any capacitor behind the two chained display, and didn't connect the Adafruit ledbar (didn't arrive yet).
Any ideas?
Thank you

**Comment by sommo** [comment]
for the loop while racing, seems about the pause button, i checked again the connection (it has already the 10k resistor but i grounded better) and now it's ok, while racing no more pause/restart.
Remains the wired about display name, because on count down, all the 8digit turn on (3..2..1..) all of them, so it seems about name and pause/restart string.

I also get an "issue" the one who wins get the losing song (no idea why) and the loser one get the victory song.

**Comment by micbay** [comment]
Regarding the 'Z' not showing up on LED.
You need to update the character array used by the library `LedControl.h`. The native library doesn't include every writable character so I edited it. It may not be clear from the readme, but the table shown there is a version I customized and then copied into my version of the library `LedControl`.

To get some extra letters copy the customized table from the readme (shown below) into the `LedConrol.h` file of your downloaded `LedControl` library, which, by default on windows, is found in folder:
`C:\Users\username\Documents\Arduino\libraries\LedControl\src`.

Open `LedControl.h` and swap the variable `const static byte charTable [ ]` with the one below.
```
const static byte charTable [] PROGMEM  = {
  //00  0         1         2          3        4         5         6         7
    B01111110,B00110000,B01101101,B01111001,B00110011,B01011011,B01011111,B01110000,
  //08  8         9         0         b          c        d         E         F
    B01111111,B01111011,B01110111,B00011111,B00001101,B00111101,B01001111,B01000111,
    B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,
    B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,
  //32                                                                        '
    B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,B00000010,
    B00000000,B00000000,B00000000,B00000000,B10000000,B00000001,B10000000,B00000000,
  //48  0         1         2          3        4         5         6         7
    B01111110,B00110000,B01101101,B01111001,B00110011,B01011011,B01011111,B01110000,
  //56  8         9
    B01111111,B01111011,B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,
  //64            A         B         C       D->d        E         F         G
    B00000000,B01110111,B01111111,B01001110,B00111101,B01001111,B01000111,B01011110,
  //72  H         I         J         K         L         M         N         O
    B00110111,B00000110,B01111100,B00000000,B00001110,B00000000,B00010101,B01111110,
  //80  P       Q->q      R->r        S       T->t        U         V         W
    B01100111,B01110011,B00000101,B01011011,B00001111,B00111110,B00000000,B00000000,
  //88  X         Y         Z         K                                       _
    B00000000,B00111011,B01101101,B00000000,B00000000,B00000000,B00000000,B00001000,
  //96          a->A        b         c         d         e       f->F        g
    B00000000,B01110111,B00011111,B00001101,B00111101,B01101111,B01000111,B01111011,
  //104 h         i       j->J        k         l         m         n         o
    B00010111,B00000100,B00111100,B00000000,B00000110,B00000000,B00010101,B00011101,
  //112 p         q         r       s->S        t         u         v        w
    B01100111,B01110011,B00000101,B01011011,B00001111,B00011100,B00000000,B00000000,
  //120 x         y       z->Z
    B00000000,B00111011,B01101101,B00000000,B00000000,B00000000,B00000000,B00000000
};
```

**Comment by micbay** [comment]
I don't fully understand what you are describing about the Pause, however, there is a bug I fixed while editing to add a Drag racing option related to the Pause button that is likely the issue.

Try going to line 1332, I believe, inside of the `ToggleRacePause()` function and swapping:
the old bad line,
```  int logMillis = millis();```
with the new bug fix line:
```unsigned long logMillis = millis();```

The integer variable type is not big enough to hold the running ms time and so it overruns and eventually the debounce time is not being honored. So, you are probably getting multiple triggers on a single press because the contact bounce is not being properly filtered.

**Comment by sommo** [comment]
> Regarding the 'Z' not showing up on LED. You need to update the character array used by the library `LedControl.h`. The native library doesn't include every writable character so I edited it. It may not be clear from the readme, but the table shown there is a version I customized and then copied into my version of the library `LedControl`.
> 
> To get some extra letters copy the customized table from the readme (shown below) into the `LedConrol.h` file of your downloaded `LedControl` library, which, by default on windows, is found in folder: `C:\Users\username\Documents\Arduino\libraries\LedControl\src`.
> 
> Open `LedControl.h` and swap the variable `const static byte charTable [ ]` with the one below.
> 
> ```
> const static byte charTable [] PROGMEM  = {
>   //00  0         1         2          3        4         5         6         7
>     B01111110,B00110000,B01101101,B01111001,B00110011,B01011011,B01011111,B01110000,
>   //08  8         9         0         b          c        d         E         F
>     B01111111,B01111011,B01110111,B00011111,B00001101,B00111101,B01001111,B01000111,
>     B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,
>     B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,
>   //32                                                                        '
>     B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,B00000010,
>     B00000000,B00000000,B00000000,B00000000,B10000000,B00000001,B10000000,B00000000,
>   //48  0         1         2          3        4         5         6         7
>     B01111110,B00110000,B01101101,B01111001,B00110011,B01011011,B01011111,B01110000,
>   //56  8         9
>     B01111111,B01111011,B00000000,B00000000,B00000000,B00000000,B00000000,B00000000,
>   //64            A         B         C       D->d        E         F         G
>     B00000000,B01110111,B01111111,B01001110,B00111101,B01001111,B01000111,B01011110,
>   //72  H         I         J         K         L         M         N         O
>     B00110111,B00000110,B01111100,B00000000,B00001110,B00000000,B00010101,B01111110,
>   //80  P       Q->q      R->r        S       T->t        U         V         W
>     B01100111,B01110011,B00000101,B01011011,B00001111,B00111110,B00000000,B00000000,
>   //88  X         Y         Z         K                                       _
>     B00000000,B00111011,B01101101,B00000000,B00000000,B00000000,B00000000,B00001000,
>   //96          a->A        b         c         d         e       f->F        g
>     B00000000,B01110111,B00011111,B00001101,B00111101,B01101111,B01000111,B01111011,
>   //104 h         i       j->J        k         l         m         n         o
>     B00010111,B00000100,B00111100,B00000000,B00000110,B00000000,B00010101,B00011101,
>   //112 p         q         r       s->S        t         u         v        w
>     B01100111,B01110011,B00000101,B01011011,B00001111,B00011100,B00000000,B00000000,
>   //120 x         y       z->Z
>     B00000000,B00111011,B01101101,B00000000,B00000000,B00000000,B00000000,B00000000
> };
> ```

didin't saw it, sorry, i corrected it, and now all letters appears, except the K, but i will change the name without K, don't know why because it's seem mapped with your custom charTable

**Comment by micbay** [comment]
'K's are not possible because it looks like an 'H'. The letters in the table are above the binary value that represents them, not below.

**Comment by sommo** [comment]
> I don't fully understand what you are describing about the Pause, however, there is a bug I fixed while editing to add a Drag racing option related to the Pause button that is likely the issue.
> 
> Try going to line 1332, I believe, inside of the `ToggleRacePause()` function and swapping: the old bad line, ` int logMillis = millis();` with the new bug fix line: `unsigned long logMillis = millis();`
> 
> The integer variable type is not big enough to hold the running ms time and so it overruns and eventually the debounce time is not being honored. So, you are probably getting multiple triggers on a single press because the contact bounce is not being properly filtered.

i also modified this and the pause is correct, anyway as before (was a problem about right grounding the button).

**Comment by sommo** [comment]
maybe i get what going wrong about victory song vs losersong.
Who wins and get second is right reported in the display, the problem is only about the song.
Racer1 no matter it will get the loser song and Racer2 will get every time the victory song.

**Comment by sommo** [comment]
> 'K's are not possible because it looks like an 'H'. The letters in the table are above the binary value that represents them. The letters are code comments, they are not actually part of the table. All of the characters whose value is `B00000000` are blank.

the only way to print K: https://www.adafruit.com/product/1911 but i feel is enough change name :D

**Comment by micbay** [comment]
Regarding Victory Song
I think this might be a confusion of intent.
The song is not related to the place, it's related to the racer. Every racer is associated with their own song, so when any given racer finishes, the song associated with that racer plays. So the same song plays for Racer 2 no matter what order they finish.

**Comment by sommo** [comment]
i completly misunderstandin the link one-to-one to song and racer.. i was thinking a song fo the winner and a song for the loser one.
thank you again, i will close the issue

**Comment by sommo** [comment]
sorry, reopening it for a question, how could i change linking racer1 to songx, racer2 to songy?
could you point me the unique link racer-song?
thank you!

**Comment by micbay** [comment]
You can edit song-racer associations by editing the song and/or racer arrays in the local settings file.

If you haven't already done so, create a `localSettings.h` file by copying and renaming the `example.localSettings.h` to `localSettings.h`, then open and edit your `defaultSettings.h` and tell it to include the `localSettings.h` settings, by uncomment the code line 15:
```// #include "localSettings.h"```
so that it looks like
```#include "localSettings.h"```

Then to adjust racer-song associations, go to the very bottom of the new `localSettings.h` file. uncomment , `RACERS_SONGS_LIST`, and move/edit the songs you want for a given racer, into the same index as the associated `RACER_NAMES_LIST`. Also, of course, the racer names can be adjusted/edited in the same manner. Make sure the racer and song arrays are always the same length.
Also, **do not** edit the 1st term of the racer name or song arrays as that is reserved for the 'no racer' condition.

If the ability to associate songs with place or to have just a single victory song for the first place finisher is a desired feature, feel free to create a possible feature discussion to document the idea for feedback.
It might be possible at some point to make that an option settable by the `localSettings` file.

**Comment by sommo** [comment]
thank you, get it! i will open a new discussion for that
