### ISSUE TITLE
ledbar doesn't turn on

### ISSUE THREAD

**Issue by sommo** [micbay/RaceTimerAndController#16]
hi @micbay,
adafruit ledbar arrive today, i've solder it, founded (with an i2c sketch scanner) that it has 0x74 address and test with the example sketch from the library and it works.
So i get back to the main sketch and modified the line 1927 into this to match the right i2c address:

  bar.begin(0x74);

but it doesn't work.
i connected the both (ledbar and LCDdisplay) SDA on A4 pin and both SCL to A5 pin to the arduino nano.
I need to wiring it different?
As always, Thank you!

**Comment by sommo** [comment]
i tried again with the i2c scanner sketch, and now reports it has 0x70, changed again the main sketch to 0x70, but nothing, ledbar can't get on... so i'm quite disoriented

**Comment by micbay** [comment]
I'm not sure what the range of input voltage is acceptable, maybe the Arduino will regulate the voltage down, but everything in this system are 5V devices. I would stay with a 5V source and make sure that the displays are pulling voltage from the 5V source directly, not through the +5V Arduino pin.
Also, to work through troubleshooting try using the example sketch 'bargraph24' until its working. the default 'bargraph24' sketch example works for me as is using the same wiring and address used for the race controller.

**Comment by sommo** [comment]
i have the arduino nano (the not original one), that its working with the 'bargraph24' sketch in a really strange behaviour, if i upload the sketch to it i need to hw reset it about 4 times before getting the ledbar on and reproducing the sketch.
Don't know why, myabe i need to invest money to an arduino nano original.. or revert the sketch to an arduino uno that i own 2 of them

**Comment by micbay** [comment]
If the Uno is working, the uno has the same processor as the nano, and should work as a drop in replacement for the nano, with the same race controller code and pinouts.
My nanos are all bootleg cheapo versions and in the past I've had to work out similar odd behavior. Your nano might have a corrupted bootloader or some other issue. You could try reflashing the bootloader or choosing a different compiler, and/or bootloader, from the Arduino IDE, and try different combinations to see if that helps.
You can also use the Uno to reflash the bootloader on the Nano, how to do that is discussed in this article on [Installing an Arduino Bootloader](https://learn.sparkfun.com/tutorials/installing-an-arduino-bootloader/all), and the abbreviated steps are given below.

**To Fix Corrupted Arduino Nano**
Wire as such (uno D10-D13 to Nano ISP header)
Then in Arduino IDE, program the Uno with the example sketch (Arduino ISP)
Then from the 'Tools' menu select 'Burn Bootloader'.
![image](https://user-images.githubusercontent.com/23461494/225692217-dbf65b34-d470-482a-84bc-f572a839987e.png)

**Comment by sommo** [comment]
i did it, i flashed the nano with the uno, now i can flash the nano with arduino with the ATmega328P so seems better, in fact i have flashed the main sketch to it but to get the ledbar on i need to hw reset (button on it) only once. better sure cause first were random the number of reset to do.

**Comment by sommo** [comment]
after changing the bootloader i notice that while it boots it sound 2 times, before flashing the nano, it sounds only 1 beep while booting.

**Comment by sommo** [comment]
anyway now i get this while uploading to the nano
avrdude: stk500_loadaddr(): (a) protocol error, expect=0x14, resp=0x10
avrdude: stk500_loadaddr(): (a) protocol error, expect=0x14, resp=0x10
avrdude: stk500_loadaddr(): (a) protocol error, expect=0x14, resp=0x10
avrdude: stk500_loadaddr(): (a) protocol error, expect=0x14, resp=0x10
avrdude: stk500_loadaddr(): (a) protocol error, expect=0x14, resp=0x10
avrdude: stk500_loadaddr(): (a) protocol error, expect=0x14, resp=0x10
avrdude: stk500_loadaddr(): (a) protocol error, expect=0x14, resp=0x10
and after a few i get it uploaded anyway

**Comment by micbay** [comment]
Sounds like maybe there is an options mismatch in the chosen board, programmer, and/or bootloader combination, Did you switch your bootloader option after flashing them to use the current 138P instead of the old one?
My nanos are fairly old, and were reflashed with the older Arduino IDE 1.8, but they work fine with the new IDE 2.0 using the following: select 'Arduino Nano' board type, use the programmer 'AVRISP mkll' and the current 'ATMega138P' bootloader. if I try using 'ATMega138P (old bootloader)', I can replicate a similar error.

**Comment by micbay** [comment]
For me, when I upload a sketch I get 3 rapid beeps after it compiles/starts the upload, and 1 beep after it finishes uploading. The Race Controller code also commands a beep on bootup.
Sometimes after an upload I need to power cycle the system, not just push the Arduino reset button, but unplug power to all devices, and plug it back in to get everything reset to an operable condition. Since not all power goes through the Arduino pushing the reset doesn't always reset displays and peripherals that are powered directly and they can end up in an odd state.

**Comment by sommo** [comment]
i would try to use the Arduino IDE 1.8 maybe i get the nano working properly but i get this while compiling:

```
/Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino: In function 'void PrintClock(ulong, byte, byte, byte, displays, byte, bool)':
/Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:1007:22: warning: converting to non-pointer type 'long unsigned int' from NULL [-Wconversion-null]
         decimalSec = NULL;
                      ^~~~
/Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino: In function 'void loop()':
/Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:1993:35: warning: invalid conversion from 'const char* const*' to 'const char**' [-fpermissive]
             UpdateLCDMenu(MainText);
                                   ^
/Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:651:6: note:   initializing argument 1 of 'void UpdateLCDMenu(const char**)'
 void UpdateLCDMenu(const char *curMenu[]){
      ^~~~~~~~~~~~~
/Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:2025:39: warning: invalid conversion from 'const char* const*' to 'const char**' [-fpermissive]
             UpdateLCDMenu(SettingsText);
                                       ^
/Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:651:6: note:   initializing argument 1 of 'void UpdateLCDMenu(const char**)'
 void UpdateLCDMenu(const char *curMenu[]){
      ^~~~~~~~~~~~~
/Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:2090:43: warning: invalid conversion from 'const char* const*' to 'const char**' [-fpermissive]
             UpdateLCDMenu(SelectRacersText);
                                           ^
/Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:651:6: note:   initializing argument 1 of 'void UpdateLCDMenu(const char**)'
 void UpdateLCDMenu(const char *curMenu[]){
      ^~~~~~~~~~~~~
/Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:2142:40: warning: invalid conversion from 'const char* const*' to 'const char**' [-fpermissive]
             UpdateLCDMenu(StartRaceText);
                                        ^
/Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:651:6: note:   initializing argument 1 of 'void UpdateLCDMenu(const char**)'
 void UpdateLCDMenu(const char *curMenu[]){
      ^~~~~~~~~~~~~
Lo sketch usa 27730 byte (90%) dello spazio disponibile per i programmi. Il massimo è 30720 byte.
Le variabili globali usano 1609 byte (78%) di memoria dinamica, lasciando altri 439 byte liberi per le variabili locali. Il massimo è 2048 byte.
```

**Comment by sommo** [comment]
anyway it compile the sketch, and upload it but still get same issue on ledbar, it doesn't turn on... i will try to move to the arduino uno and let you know.

**Comment by sommo** [comment]
For me, when I upload a sketch I get 3 rapid beeps after it compiles/starts the upload, and 1 beep after it finishes uploading. The Race Controller code also commands a beep on bootup.
=> me too but i still have ledbar always off

**Comment by sommo** [comment]
you could not believe in this...: i order 2 ledbar adafruit (cause was convenient).
i just completed to soldered the second one, and with that all works like shold do...
i plugged back the first adafruit ledbar and it comes out that it changes address to 0x74, like i have noticed before... seems something wrong on it.. could it be a soldering problem? i don't know if i could try to soldered one of the couple behind A0/A1/A2 to force a fixed i2c address.. never done before

**Comment by sommo** [comment]
forced to use 0x74 and seems good also with the first ledbar. i will close the issue, thank you @micbay

**Comment by micbay** [comment]
Maybe there is a bad solder joint on the address resistors which is causing it to have an intermittent connection, which in turn is causing the address to change as the bad solder joint comes in and out of connection. Double check the solder joints on the resistors, and possibly the chip too. If you feel confident with a soldering iron you can just go around each solder joint and briefly heat them to rewet the solder. The solder will automatically pull itself around the pin and solder pads, fixing any cracked solder joints that might be there.
![image](https://user-images.githubusercontent.com/23461494/225943446-7c5ade6a-e798-4bed-ba08-680797b9d828.png)

To get an address of `0x74` suggests the board thinks that jumper pad `A2` is shorted.

For folks coming to this thread later, here is the [Adafruit I2C addressing guidance](https://learn.adafruit.com/adafruit-led-backpack/changing-i2c-address), and the gist is reprinted below.

Possible I2C addresses for Bi-color 24-bargraph: `0x70`, `0x71`, `0x72`, `0x73`, `0x74`, `0x75`, `0x76`, `0x77`
![image](https://user-images.githubusercontent.com/23461494/225939895-2c8e4766-2c74-4835-b265-de60ffaa28cd.png)
Set the address by shorting the pads on the jumper resistors, shown above.
- `A0` sets the lowest bit with a value of 1,
- `A1` sets the middle bit with a value of 2.
- `A2` sets the high bit with a value of 4.
- The final address is `0x70` + `A2` + `A1` + `A0`.
- Example: if `A2` is shorted and `A0` is shorted, the address is `0x70` + 4 + 1 = `0x75`. If only `A1` is shorted, the address is `0x70` + 2 = `0x72`

**Comment by micbay** [comment]
> i would try to use the Arduino IDE 1.8 maybe i get the nano working properly but i get this while compiling:
> 
> ```
> /Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino: In function 'void PrintClock(ulong, byte, byte, byte, displays, byte, bool)':
> /Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:1007:22: warning: converting to non-pointer type 'long unsigned int' from NULL [-Wconversion-null]
>          decimalSec = NULL;
>                       ^~~~
> /Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino: In function 'void loop()':
> /Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:1993:35: warning: invalid conversion from 'const char* const*' to 'const char**' [-fpermissive]
>              UpdateLCDMenu(MainText);
>                                    ^
> /Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:651:6: note:   initializing argument 1 of 'void UpdateLCDMenu(const char**)'
>  void UpdateLCDMenu(const char *curMenu[]){
>       ^~~~~~~~~~~~~
> /Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:2025:39: warning: invalid conversion from 'const char* const*' to 'const char**' [-fpermissive]
>              UpdateLCDMenu(SettingsText);
>                                        ^
> /Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:651:6: note:   initializing argument 1 of 'void UpdateLCDMenu(const char**)'
>  void UpdateLCDMenu(const char *curMenu[]){
>       ^~~~~~~~~~~~~
> /Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:2090:43: warning: invalid conversion from 'const char* const*' to 'const char**' [-fpermissive]
>              UpdateLCDMenu(SelectRacersText);
>                                            ^
> /Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:651:6: note:   initializing argument 1 of 'void UpdateLCDMenu(const char**)'
>  void UpdateLCDMenu(const char *curMenu[]){
>       ^~~~~~~~~~~~~
> /Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:2142:40: warning: invalid conversion from 'const char* const*' to 'const char**' [-fpermissive]
>              UpdateLCDMenu(StartRaceText);
>                                         ^
> /Users/sommo/Downloads/RaceTimerAndController-StartLightI2C 3/RaceTimerAndController/RaceTimerAndController.ino:651:6: note:   initializing argument 1 of 'void UpdateLCDMenu(const char**)'
>  void UpdateLCDMenu(const char *curMenu[]){
>       ^~~~~~~~~~~~~
> Lo sketch usa 27730 byte (90%) dello spazio disponibile per i programmi. Il massimo è 30720 byte.
> Le variabili globali usano 1609 byte (78%) di memoria dinamica, lasciando altri 439 byte liberi per le variabili locali. Il massimo è 2048 byte.
> ```

I'm not sure what this is. I note that it's pointing to your windows `Downloads` folder though which seems odd. You had a weird path on another error you posted in another thread too. You might be somehow, accidentally using files that are in the wrong folder, If you download the code repo and then open it from inside the downloads folder, or are copying files that are not actually unzipped, but appear to be in the file navigator, that might be creating a file reference issue. Accidentally using an unzipped file or opening the `.ino` file from an unexpected directory could be throwing off the Arduino IDEs expected file paths used when it compiles  the `#include` files and libraries. Same thing goes if you downloaded libraries manually, instead of through the Adruino Library manager interface. If you see an error referencing a file path including the names of one of them.

Double check that you are always working from the `.ino` file in this directory:
`C:\Users\winusername\Documents\Arduino\RaceTimerAndController`

and, double check that your Arduino IDE's path settings makes sense:
For Arduino IDE 2.0 go to `File->Preferences->Settings` and make sure your 'Sketchbook location:' is still where you want it. By default it should be pointing to `c:\Users\winusername\Documents\Arduino`
